WebApplication2/WebApplication2/Controllers/InvoiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication2.DAL;
using WebApplication2.Models;
using MvcFlashMessages;

namespace WebApplication2.Controllers
{
    public class InvoiceController : Controller
    {
        private DBcontext db = new DBcontext();

        public ActionResult InvoiceForm(int id)
        {
            InvoiceModel invoice = db.Invoices.Find(id);
            return View(invoice);
        }

        [HttpPost]
        public ActionResult InvoiceForm(InvoiceModel newInvoice, int id)
        {
            if(ModelState.IsValid)
            {
                var invoice = db.Invoices.Find(id);
                invoice.Status = "Paid";
                invoice.Date = DateTime.Today;
                invoice.Card = newInvoice.Card;
                invoice.CardOwner = newInvoice.CardOwner;
                invoice.CVC = newInvoice.CVC;
                invoice.Amount = newInvoice.Amount;
                db.SaveChangesAsync();
                this.Flash("success", "Added!");
                return RedirectToAction("RentList", "Rent");
            }
            this.Flash("error", "Failed!");
            return View();
        }
    }
}

WebApplication2/WebApplication2/Controllers/RentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication2.DAL;
using WebApplication2.Models;
using MvcFlashMessages;
using DataLibrary.DataAccess;

namespace WebApplication2.Controllers
{
    public class RentController : Controller
    {
        private DBcontext db = new DBcontext();

        // GET: Rent
        public ActionResult RentList()
        {
            return View(db.Rents.ToList());
        }

        public ActionResult DeclineRent(int id)
        {
            var Rent = db.Rents.Find(id);
            db.Rents.Remove(Rent);
            db.SaveChanges();
            this.Flash("success", "Removed!");
            return RedirectToAction("RentList");
        }

        public ActionResult Rent()
        {
            var items = db.Items.ToList();
            List<string> selection = new List<string>();
            foreach (var item in items)
            {
                selection.Add(item.Name);
            }
            
            ViewData["selection"] = selection;
            return View();
        }

        [HttpPost]
        public ActionResult Rent(RentModel rent)
        {
            var items = db.Items.ToList();
            List<string> selection = new List<string>();
            foreach (var item in items)
            {
                selection.Add(item.Name);
            }
            ViewData["selection"] = selection;

            if (ModelState.IsValid)
            {
                if (Request["Items"] != null || rent.StartDate > rent.EndDate)
                {
                    var it = Request["Items"];
                    var item = db.Items.Where(x => x.Name == it).SingleOrDefault();

                    if (item == null)
                    {
                        this.Flash("error", "Failed!");
                        return View();
                    }

                    InvoiceModel invoice = new InvoiceModel();
                    invoice.Status = "Unpaid";
                    invoice.Amount = item.Price * (rent.EndDate - rent.StartDate).TotalDays;
                    invoice.Date = DateTime.Today;
                    invoice.CVC = 100;
                    invoice.CardOwner = "-";
                    invoice.Card = 0;

                    var checkBox = Request.Form["checkBox"];

                    string tID = null;
                    string itID = null;
                    string inID = null;
                    string inID2 = null;

                    itID = item.Id.ToString();

                    if (checkBox!= null)
                    {
                        TransportRequestModel transport = new TransportRequestModel();
                        transport.Delivery_Time = rent.StartDate;
                        transport.Pickup_Time = rent.EndDate;
                        transport.Status = "Created";
                        //db.TransportRequests.Add(transport);
                        rent.Transport = transport;

                        string sql = @"insert into dbo.Transport (Pickup_Time, Delivery_Time, Status, Notes) values (@Pickup_Time, @Delivery_Time, @Status, @Notes); SELECT MAX(ID) FROM dbo.Transport;";
                        tID = (SqlDataAccess.SaveData(sql, transport)).ToString();
                        tID = db.TransportRequests.OrderByDescending(u => u.Id).FirstOrDefault().Id.ToString();


                        InvoiceModel invoice2 = new InvoiceModel();
                        invoice2.Status = "Unpaid";
                        invoice2.Amount = item.Price * (rent.EndDate - rent.StartDate).TotalDays;
                        invoice2.Date = DateTime.Today;
                        invoice2.CVC = 100;
                        invoice2.CardOwner = "-";
                        invoice2.Card = 0;

                        string sqles = @"insert into dbo.Invoice (Amount, Date, Status, Card, CardOwner, CVC) values (@Amount, @Date, @Status, @Card, @CardOwner, @CVC); SELECT MAX(ID) FROM dbo.Invoice;";
                        inID2 = (SqlDataAccess.SaveData(sqles, invoice2)).ToString();
                        inID2 = db.Invoices.OrderByDescending(u => u.Id).FirstOrDefault().Id.ToString();
                    }

                    rent.Status = "In rent";
                    rent.Invoice = invoice;
                    rent.Item = item;
                    rent.Comments = item.Description;

                    string sqle = @"insert into dbo.Invoice (Amount, Date, Status, Card, CardOwner, CVC) values (@Amount, @Date, @Status, @Card, @CardOwner, @CVC); SELECT MAX(ID) FROM dbo.Invoice;";
                    inID = (SqlDataAccess.SaveData(sqle, invoice)).ToString();
                    inID = db.Invoices.OrderByDescending(u => u.Id).FirstOrDefault().Id.ToString();

                    if (checkBox != null)
                    {
                        sqle = @"insert into dbo.Rent (StartDate, EndDate, Comments, Transport_Id, Item_Id, Invoice_Id, InvoiceT_Id) values (@StartDate, @EndDate, @Comments, " + tID+", "+itID+", "+inID+", "+inID2+");";
                        SqlDataAccess.SaveData(sqle, rent);
                    }
                    else
                    {
                        sqle = @"insert into dbo.Rent (StartDate, EndDate, Comments, Item_Id, Invoice_Id) values (@StartDate, @EndDate, @Comments, " + itID+", "+inID+");";
                        SqlDataAccess.SaveData(sqle, rent);
                    }
                    

                    //db.Invoices.Add(invoice);
                    //db.Rents.Add(rent
                    this.Flash("success", "Added!");
                    return RedirectToAction("RentList");
                }
                this.Flash("error", "Failed!");
                return View();
            }
            this.Flash("error", "Failed!");
            return View();
        }
    }
}

WebApplication2/WebApplication2/Views/Rent/Rent.cshtml
@model WebApplication2.Models.RentModel

@{
    ViewBag.Title = "Rent";
    List<String> selection = (List<string>)ViewData["selection"];
}

<h2>Rent</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        <label class="control-label col-md-2">Item</label>
        <div class="col-md-10">
            @Html.DropDownList("Items", new SelectList(selection), "Select a item...")
            @Html.ValidationMessageFor(model => model.Item, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control", type = "date" } })
            @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control", type = "date" } })
            @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-check">
        <label class="form-check-label col-md-2" for="checkbox1">Do you need shipping?</label>
        <div class="col-md-offset-2">
            <input type="checkbox" class="form-check-input" id="checkbox1" name="checkBox">
        </div>        
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Rent" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "Home")
</div>

WebApplication2/WebApplication2/Views/Rent/RentList.cshtml
@model IEnumerable<WebApplication2.Models.RentModel>

@{
    ViewBag.Title = "Rent List";
}

<h2>Rent List</h2>

<table class="table">
    <tr>
        <th>
            Start date
        </th>
        <th>
            End date
        </th>
        <th>
            Status
        </th>
        <th>
            Comments
        </th>
        <th>
            Item name
        </th>
        <th>
            Item price
        </th>
        <th>
            Invoice status
        </th>
        <th>
            Transport invoice status
        </th>
        <th></th>
    </tr>
    @if (Model != null)
    {
        foreach (var item in Model)
        {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.StartDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EndDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Status)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Comments)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Invoice.Status)
        </td>
        <td>
            @if (item.InvoiceT != null)
            { @Html.DisplayFor(modelItem => item.InvoiceT.Status)}
        </td>
        <td>
            @if (item.StartDate > DateTime.Now)
            {
                <button type="button" class="btn btn-info" data-toggle="modal" data-target="#myModal">Cancel Rent</button>
                <!-- Modal -->
                <div class="modal fade" id="myModal" role="dialog">
                    <div class="modal-dialog">

                        <!-- Modal content-->
                        <div class="modal-content">
                            <div class="modal-header">
                                <h4 class="modal-title">Are you sure you want to cancel rent?</h4>
                            </div>
                            <div class="modal-body">
                                @Html.ActionLink("Yes", "DeclineRent", new { id = item.Id }, new { @class = "btn btn-default" })
                                <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                            </div>
                        </div>

                    </div>
                </div>
            }
            @if (item.Invoice.Status != "Paid")
            {
                @Html.ActionLink("Pay for rent", "InvoiceForm", "Invoice", new { id = item.Invoice.Id }, new { @class = "btn btn-info" });
            }
            @if (item.InvoiceT != null && item.InvoiceT.Status != "Paid")
            {
                @Html.ActionLink("Pay for transport", "InvoiceForm", "Invoice", new { id = item.InvoiceT.Id }, new { @class = "btn btn-info" });
            }
        </td>
    </tr>
        }
    }

</table>